### ISSUE TITLE
Avoid <functional>?

### ISSUE THREAD

**Issue by vinniefalco** [groundswellaudio/swl-variant#1]
Does the C++ specification allow you to forward-declare the `std::hash` class template? If so, this would let you specialize it without the need to include `<functional>`.

**Comment by groundswellaudio** [comment]
AFAIK there is no exceptions in the standard to the "no user declarations in `std`" rule for `std::hash`.

**Comment by vinniefalco** [comment]
What about if you include `<typeindex>` (which is very lightweight) instead of `<functional>` to get the primary template?

**Comment by groundswellaudio** [comment]
This would work to write the specialization for `variant` but we would still need the implementation of `std::hash` for builtin types which is in `<functional>`.

**Comment by vinniefalco** [comment]
UGH you're right.
